#name: qibla_guide_new
name: qibla
description: "Our Qibla Guide app provides accurate Qibla direction wherever you are, ensuring precise alignment during prayers. It offers real-time updates and is your trusted companion for maintaining spiritual connection and devotion"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_qiblah: ^3.0.3
  vibration: ^1.9.0
  flutter_svg: ^2.0.10+1
  geolocator: 11.1.0
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1

  #  Firebase
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  firebase_in_app_messaging: ^0.7.5+7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  #  fonts:
  #    - family: leagueSpartan
  #      fonts:
  #        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
  #    - family: poppins
  #      fonts:
  #        - asset: assets/fonts/Poppins-Regular.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
